### ISSUE TITLE
Trouble running/installing

### ISSUE THREAD

**Issue by afonsoalmeida** [nickng/dingo-hunter#26]
Hello!

I have been trying to use this tool using the CFSM approach, but I have not been able to.
I followed the instructions and I can't seem to run the line "dingo-hunter cfsms --prefix deadlock example/local-deadlock/main.go", it says that the dingo-hunter command is not found.
Additionally, the "go get -u github.com/nickng/dingo-hunter" at the end issues a "code in directory /home/afonso/go_projects/src/github.com/nickng/migo expects import "github.com/nickng/migo".
I'm not sure if I made any mistake following the installation process, but any help would be much appreciated.

Thank you!

**Comment by nickng** [comment]
Hi there :wave: 
The project is not actively being maintained, but it looks like the installation problems is because the code hasn't been migrated to Go modules. Could you try the `gomod-migration` branch and see if that work for you?

**Comment by afonsoalmeida** [comment]
Thanks for the attention.
I believe you have fixed my problem, but now when running the example (./runsmc inputs/deadlock_cfsms 2) from the README I run into another problem:

----------------- GMC Check -----------------
Parsing CFSMs file... (factor 2)
Machine 5: False
Machine 3: True
Machine 4: False
Machine 2: False

Traceback (most recent call last):
  File "./runsmc.py", line 55, in <module>
    subprocess.check_call([PETRY,"-dead","-ip",mybasename+"_toPetrify","-o","tempefc"])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'
